version: 2

aliases: [
  &dependency-paths [
    "node_modules",
    "packages/dollie-cli/node_modules",
    "packages/dollie-utils/node_modules",
    "packages/dollie-core/node_modules",
    "packages/dollie-origins/node_modules",
    "checksum.txt",
  ],
  &output-paths [
    "packages/dollie-cli/lib",
    "packages/dollie-utils/lib",
    "packages/dollie-core/lib",
    "packages/dollie-origins/lib",
    "checksum.txt",
  ],
]

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.14

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npx lerna bootstrap
      - run: npm run checksum
      - save_cache:
          paths: *dependency-paths
          key: v1-dependencies-{{ checksum "checksum.txt" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "checksum.txt" }}
      - run: ls -al packages/dollie-core
      - run: npm run build
      - run: ls -al packages/dollie-core
      - save_cache:
          paths: *output-paths
          key: v1-dist-{{ checksum "checksum.txt" }}

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dist-{{ checksum "checksum.txt" }}
            - v1-dependencies-{{ checksum "checksum.txt" }}
      - run: ls -al
      - run: npm run publish

  deploy_docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "checksum.txt" }}
            - v1-dependencies-
      - run: npm run docs:build
      - run: npm run docs:deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only:
                - /^dollie@(\d+)\.(\d+)\.(\d+).*/
            branches:
              ignore: /.*/
      - deploy_docs:
          requires:
            - install
          filters:
            tags:
              only:
                - /^docs-.*/
            branches:
              ignore: /.*/
