version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.14

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npx lerna bootstrap
      - run: npm run checksum
      - save_cache:
          paths:
            - packages/@dollie/cli/node_modules
            - packages/@dollie/core/node_modules
            - packages/@dollie/origins/node_modules
            - node_modules
            - checksum.txt
          key: v1-dependencies-{{ checksum "checksum.txt" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "checksum.txt" }}
            - v1-dependencies-
      - run: ls -al packages/@dollie/core
      - run: npx lerna run build
      - run: ls -al packages/@dollie/core
      - save_cache:
          paths:
            - node_modules
            - checksum.txt
          key: v1-dependencies-{{ checksum "checksum.txt" }}
      - save_cache:
          paths:
            - packages/@dollie/cli/lib
            - packages/@dollie/core/lib
            - packages/@dollie/origins/lib
            - checksum.txt
          key: v1-dist-{{ checksum "checksum.txt" }}

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dist-{{ checksum "checksum.txt" }}
            - v1-dist-
            - v1-dependencies-{{ checksum "checksum.txt" }}
            - v1-dependencies-
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: ls -al
      - run: npm publish --access public

  deploy_docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "checksum.txt" }}
            - v1-dependencies-
      - run: npm run docs:build
      - run: npm run docs:deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
      - deploy_docs:
          requires:
            - install
          filters:
            tags:
              only:
                - /^docs-.*/
            branches:
              ignore: /.*/
